// @ts-nocheck

export function generateInvoiceEmailSubject(
  invoice: { invoiceNumber: string; total: number; currency: string },
  company: { name: string },
  template?: string
): string {
  const tpl = template || 'Invoice {invoiceNumber} from {companyName}'
  return tpl
    .replace('{invoiceNumber}', invoice.invoiceNumber)
    .replace('{companyName}', company.name)
    .replace('{total}', `${invoice.total.toFixed(2)} ${invoice.currency}`)
}

export function generateInvoiceEmailTemplate(
  invoice: {
    invoiceNumber: string
    total: number
    currency: string
    subtotal: number
    vatTotal: number
    dueDate: string | Date
    issueDate: string | Date
    paymentMethod?: string
  },
  client: { name: string; contactPerson?: string },
  company: { name: string; email?: string; bankAccount?: string; bankName?: string }
): string {
  const dueDate = new Date(invoice.dueDate).toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })
  const issueDate = new Date(invoice.issueDate).toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })
  const greeting = client.contactPerson ? `Dear ${client.contactPerson}` : `Dear ${client.name}`

  return `
<div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; color: #334155;">
  <div style="background: linear-gradient(135deg, #4f46e5, #7c3aed); padding: 32px; border-radius: 12px 12px 0 0;">
    <h1 style="color: white; margin: 0; font-size: 20px;">Invoice ${invoice.invoiceNumber}</h1>
    <p style="color: rgba(255,255,255,0.8); margin: 8px 0 0; font-size: 14px;">from ${company.name}</p>
  </div>

  <div style="padding: 32px; background: white; border: 1px solid #e2e8f0; border-top: none;">
    <p style="font-size: 15px; line-height: 1.6;">${greeting},</p>

    <p style="font-size: 15px; line-height: 1.6;">
      Please find attached invoice <strong>${invoice.invoiceNumber}</strong> issued on ${issueDate}.
    </p>

    <div style="background: #f8fafc; border-radius: 8px; padding: 20px; margin: 24px 0;">
      <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
        <tr>
          <td style="padding: 6px 0; color: #64748b;">Invoice Number</td>
          <td style="padding: 6px 0; text-align: right; font-weight: 600;">${invoice.invoiceNumber}</td>
        </tr>
        <tr>
          <td style="padding: 6px 0; color: #64748b;">Net Amount</td>
          <td style="padding: 6px 0; text-align: right;">${invoice.subtotal.toFixed(2)} ${invoice.currency}</td>
        </tr>
        <tr>
          <td style="padding: 6px 0; color: #64748b;">VAT</td>
          <td style="padding: 6px 0; text-align: right;">${invoice.vatTotal.toFixed(2)} ${invoice.currency}</td>
        </tr>
        <tr style="border-top: 1px solid #e2e8f0;">
          <td style="padding: 12px 0 6px; font-weight: 700; font-size: 16px;">Total Due</td>
          <td style="padding: 12px 0 6px; text-align: right; font-weight: 700; font-size: 16px; color: #4f46e5;">${invoice.total.toFixed(2)} ${invoice.currency}</td>
        </tr>
        <tr>
          <td style="padding: 6px 0; color: #64748b;">Due Date</td>
          <td style="padding: 6px 0; text-align: right; font-weight: 600; color: ${new Date(invoice.dueDate) < new Date() ? '#ef4444' : '#334155'};">${dueDate}</td>
        </tr>
      </table>
    </div>

    ${company.bankAccount ? `
    <div style="background: #f0fdf4; border-radius: 8px; padding: 16px; margin: 24px 0;">
      <p style="margin: 0 0 8px; font-weight: 600; font-size: 14px; color: #166534;">Payment Details</p>
      <p style="margin: 0; font-size: 13px; color: #15803d;">
        ${company.bankName ? `Bank: ${company.bankName}<br/>` : ''}
        Account: ${company.bankAccount}
      </p>
    </div>
    ` : ''}

    <p style="font-size: 14px; line-height: 1.6; color: #64748b;">
      If you have any questions regarding this invoice, please don't hesitate to contact us.
    </p>

    <p style="font-size: 14px; line-height: 1.6;">
      Thank you for your business.<br/>
      <strong>${company.name}</strong>
    </p>
  </div>

  <div style="padding: 16px 32px; background: #f8fafc; border-radius: 0 0 12px 12px; border: 1px solid #e2e8f0; border-top: none;">
    <p style="margin: 0; font-size: 12px; color: #94a3b8; text-align: center;">
      This invoice was generated by Fakturator &middot; ${company.email || ''}
    </p>
  </div>
</div>`.trim()
}

export function generateReminderEmailTemplate(
  invoice: any,
  client: any,
  company: any,
  daysOverdue: number
): string {
  const greeting = client.contactPerson ? `Dear ${client.contactPerson}` : `Dear ${client.name}`
  const dueDate = new Date(invoice.dueDate).toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })

  return `
<div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 600px; margin: 0 auto; color: #334155;">
  <div style="background: #f59e0b; padding: 24px; border-radius: 12px 12px 0 0;">
    <h1 style="color: white; margin: 0; font-size: 18px;">Payment Reminder</h1>
  </div>
  <div style="padding: 32px; background: white; border: 1px solid #e2e8f0; border-top: none; border-radius: 0 0 12px 12px;">
    <p>${greeting},</p>
    <p>This is a friendly reminder that invoice <strong>${invoice.invoiceNumber}</strong> for <strong>${invoice.total.toFixed(2)} ${invoice.currency}</strong> was due on ${dueDate} (${daysOverdue} days ago).</p>
    <p>Please arrange payment at your earliest convenience.</p>
    <p>Thank you,<br/><strong>${company.name}</strong></p>
  </div>
</div>`.trim()
}
