[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NEXT_PUBLIC_BASE_URL = "https://fakturator-app.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"
